// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADn2ajx1PUkFX8uCD1NCPMs3yRqs2d3l0',
    appId: '1:579742994775:web:68ec22dbf1e83f4558ee12',
    messagingSenderId: '579742994775',
    projectId: 'smarttask-84b8d',
    authDomain: 'smarttask-84b8d.firebaseapp.com',
    storageBucket: 'smarttask-84b8d.firebasestorage.app',
    measurementId: 'G-Z6GMJR98RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-_heteDqEr7IG4IM8f6YbFWwOdP4d3Vg',
    appId: '1:579742994775:android:35d30b3381f0cb5758ee12',
    messagingSenderId: '579742994775',
    projectId: 'smarttask-84b8d',
    storageBucket: 'smarttask-84b8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz7befmtZLISdg1lt4A5k3uFcYaIu4jLs',
    appId: '1:579742994775:ios:a85330e7934a4f0b58ee12',
    messagingSenderId: '579742994775',
    projectId: 'smarttask-84b8d',
    storageBucket: 'smarttask-84b8d.firebasestorage.app',
    iosBundleId: 'com.example.smartTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz7befmtZLISdg1lt4A5k3uFcYaIu4jLs',
    appId: '1:579742994775:ios:a85330e7934a4f0b58ee12',
    messagingSenderId: '579742994775',
    projectId: 'smarttask-84b8d',
    storageBucket: 'smarttask-84b8d.firebasestorage.app',
    iosBundleId: 'com.example.smartTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADn2ajx1PUkFX8uCD1NCPMs3yRqs2d3l0',
    appId: '1:579742994775:web:7756f7c75276be9258ee12',
    messagingSenderId: '579742994775',
    projectId: 'smarttask-84b8d',
    authDomain: 'smarttask-84b8d.firebaseapp.com',
    storageBucket: 'smarttask-84b8d.firebasestorage.app',
    measurementId: 'G-V0XJ9W4T15',
  );
}
